#include "test_helpers.h"
#include "roms/generated/test_and.h"   // auto-generated by: make -f src/build.mk roms

// ============================================================
// Tier-2 ROM test: test_and.s assembled with real Score7 GAS.
//
// The ROM was written in GAS assembly (tests/roms/test_and.s) and
// assembled with score-elf-as (binutils 2.25).  The generated
// uint32_t array is in tests/roms/generated/test_and.h.
//
// Notes on encoding compatibility:
//   Instructions marked [real GAS] in test_and.s use their native
//   Score7 encoding and are decoded correctly by the emulator:
//     and / and.c   (F6_ANDX=0x10 matches GAS func6)
//     or  / nop     (F6_ORX=0x11, F6_NOP=0x00 match GAS)
//
//   Instructions marked [emulator] use GAS .macro wrappers that emit
//   .long directives with the emulator's non-standard encoding.
//   They are listed in tests/roms/emul_score7.inc and will become
//   native mnemonics once the emulator's opcode/func6 table is fixed.
// ============================================================

TEST_F(ROMFixture, ANDX_GAS_ROM_Passes)
{
    runROM(rom_test_and, rom_test_and_len);
    EXPECT_TRUE(romPassed())
        << "ROM result: 0x" << std::hex << romResult()
        << "  (expected PASS_VALUE 0x" << PASS_VALUE << ")";
}

// Mutation test: flip a bit in the expected value so the comparison fails.
// Verifies the ROM harness catches incorrect results — the FAIL path runs
// and reports error code 1.
TEST_F(ROMFixture, ANDX_GAS_ROM_FailsOnWrongExpected)
{
    // Same program but word [3] is changed to expect 0x0001 instead of 0x000F.
    // addi_e r4, 0x0001  →  encodeADDIX(4, 0x0001, false)
    //   = 0x80000000 | (1<<26) | (4<<21) | 0 | (1<<1) = 0x84800002
    std::vector<uint32_t> mutated(rom_test_and, rom_test_and + rom_test_and_len);
    mutated[3] = 0x84800002u;   // wrong expected value → forces FAIL path

    runROM(mutated.data(), mutated.size());
    EXPECT_FALSE(romPassed());
    EXPECT_EQ(romResult(), 1u) << "Expected error code 1 from FAIL path";
}
