#!/usr/bin/env python3
"""bin_to_cpp.py — Convert a flat big-endian Score7 binary to a C++ header.

Usage:
    python3 bin_to_cpp.py <input.bin> <output.h> [array_name]

The binary must have been produced by:
    score-elf-objcopy -O binary --only-section=.text <elf> <output.bin>

The output is a C++ header declaring:
    static const uint32_t <array_name>[]
    static const size_t   <array_name>_len

The array values are the big-endian 32-bit instruction words exactly as the
emulator expects them (bus.ram[] stores uint32_t word values, not bytes).
"""

import struct
import sys
import os
import datetime

def main():
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <input.bin> <output.h> [array_name]",
              file=sys.stderr)
        sys.exit(1)

    input_path  = sys.argv[1]
    output_path = sys.argv[2]
    if len(sys.argv) >= 4:
        array_name = sys.argv[3]
    else:
        base = os.path.splitext(os.path.basename(input_path))[0]
        array_name = "rom_" + base.replace("-", "_").replace(".", "_")

    with open(input_path, "rb") as f:
        data = f.read()

    if len(data) % 4 != 0:
        # Pad to 4-byte boundary (Score7 instructions are always 32-bit here)
        data += b"\x00" * (4 - len(data) % 4)

    count = len(data) // 4
    words = struct.unpack(f">{count}I", data)   # big-endian uint32_t

    src_name   = os.path.basename(input_path)
    guard_name = (array_name.upper() + "_H")

    lines = [
        f"// Auto-generated by bin_to_cpp.py from {src_name}",
        f"// Generated: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"// {count} instruction word(s)",
        f"//",
        f"// DO NOT EDIT — regenerate with: make -f src/build.mk roms",
        f"",
        f"#pragma once",
        f"#include <cstdint>",
        f"#include <cstddef>",
        f"",
        f"static const uint32_t {array_name}[] = {{",
    ]

    for i, w in enumerate(words):
        lines.append(f"    0x{w:08X}u,  // [{i:3d}]  word address 0x{i:04X}")

    lines += [
        f"}};",
        f"",
        f"static const size_t {array_name}_len ="
        f" sizeof({array_name}) / sizeof({array_name}[0]);",
        f"",
    ]

    with open(output_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"[bin_to_cpp] {src_name} → {os.path.basename(output_path)}"
          f"  ({count} words, array '{array_name}')")

if __name__ == "__main__":
    main()
